-- Tablas de Usuarios (ejecutar después de 1. crear_base_datos.sql)
USE patitas_rescate;

-- Tabla de Clientes
CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    DIDENTIDAD_CLIENTE VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(255),
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_clientes_didentidad ON CLIENTES(DIDENTIDAD_CLIENTE);

-- Tabla de Mascotas
CREATE TABLE IF NOT EXISTS MASCOTAS (
    ID_MASCOTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    ESPECIE VARCHAR(50) NOT NULL,
    RAZA VARCHAR(50),
    MESES INT CHECK (MESES >= 0),
    CONSTRAINT fk_mascotas_clientes FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE INDEX idx_mascotas_cliente ON MASCOTAS(ID_CLIENTE);

-- Tabla de Veterinarios
CREATE TABLE IF NOT EXISTS VETERINARIOS (
    ID_VETERINARIO INT AUTO_INCREMENT PRIMARY KEY,
    DIDENTIDAD_VETERINARIO VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    ESPECIALIDAD VARCHAR(100),
    TELEFONO VARCHAR(15),
    CORREO VARCHAR(100) UNIQUE,
    ROL VARCHAR(20)
);

-- Tabla de Usuarios (autenticación)
CREATE TABLE IF NOT EXISTS USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    CORREO VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    CONSTRAINT fk_usuarios_clientes FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE INDEX idx_usuarios_cliente ON USUARIOS(ID_CLIENTE);

-- Datos semilla: veterinarios
INSERT INTO VETERINARIOS (ID_VETERINARIO, DIDENTIDAD_VETERINARIO, NOMBRE, ESPECIALIDAD, TELEFONO, CORREO, ROL)
VALUES (1, 'VET123456789', 'Dr. Juan Pérez', 'Estética Canina', '88881234', 'juan.perez@veterinaria.com', 'Estético');

INSERT INTO VETERINARIOS (ID_VETERINARIO, DIDENTIDAD_VETERINARIO, NOMBRE, ESPECIALIDAD, TELEFONO, CORREO, ROL)
VALUES (2, 'VET987654321', 'Dra. María López', 'Estética Felina', '88885678', 'maria.lopez@veterinaria.com', 'Estético');

INSERT INTO VETERINARIOS (ID_VETERINARIO, DIDENTIDAD_VETERINARIO, NOMBRE, ESPECIALIDAD, TELEFONO, CORREO, ROL)
VALUES (3, 'VET456789123', 'Dr. Carlos Ramírez', 'Estética General', '88889012', 'carlos.ramirez@veterinaria.com', 'Estético');
