-- Tablas de Citas y Facturas (ejecutar después de 2 y 3)
USE patitas_rescate;

-- Tabla de Citas
CREATE TABLE IF NOT EXISTS CITAS (
    ID_CITA INT AUTO_INCREMENT PRIMARY KEY,
    ID_MASCOTA INT NOT NULL,
    ID_VETERINARIO INT NOT NULL,
    FECHA_CITA DATETIME NOT NULL,
    ESTADO VARCHAR(20) NOT NULL CHECK (ESTADO IN ('Activa', 'Completada', 'Cancelada')),
    CONSTRAINT fk_citas_mascotas FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS(ID_MASCOTA),
    CONSTRAINT fk_citas_veterinarios FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIOS(ID_VETERINARIO)
);

CREATE INDEX idx_citas_mascota ON CITAS(ID_MASCOTA);
CREATE INDEX idx_citas_veterinario ON CITAS(ID_VETERINARIO);
CREATE INDEX idx_citas_estado_fecha ON CITAS(ESTADO, FECHA_CITA);

-- Tabla de Facturas
CREATE TABLE IF NOT EXISTS FACTURAS (
    ID_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_FACTURA DATETIME NOT NULL DEFAULT NOW(),
    TOTAL DECIMAL(10,2) NOT NULL CHECK (TOTAL >= 0)
);

-- Tabla de Relación entre Citas y Servicios
CREATE TABLE IF NOT EXISTS CITAS_SERVICIOS (
    ID_CITA_SERVICIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CITA INT NOT NULL,
    ID_SERVICIO INT NOT NULL,
    FACTURAS_ID_FACTURA INT,
    CONSTRAINT fk_citas_servicios_citas FOREIGN KEY (ID_CITA) REFERENCES CITAS(ID_CITA),
    CONSTRAINT fk_citas_servicios_servicios FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIOS(ID_SERVICIO),
    CONSTRAINT fk_citas_servicios_facturas FOREIGN KEY (FACTURAS_ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA)
);

CREATE INDEX idx_citasserv_cita ON CITAS_SERVICIOS(ID_CITA);
CREATE INDEX idx_citasserv_servicio ON CITAS_SERVICIOS(ID_SERVICIO);
CREATE INDEX idx_citasserv_factura ON CITAS_SERVICIOS(FACTURAS_ID_FACTURA);
